language: node_js
node_js:
- stable

script: bash ./deploy.sh
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: out
  on:
    branch: master
